language: generic
sudo: required
services:
  -docker

before_install:
  - docker build -t chalukya4619/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chalukya4619/docker-react npm run test
  
deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'docker'
  env: 'docker-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-315831907573'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY